CREATE TABLE Persons(
    IDPERSONS INT NOT NULL,
    CPF VARCHAR(15) NOT NULL ,
    NAME VARCHAR (100),
    STREET VARCHAR(125),
    NUMBERHOME INT,
    DISTRICT VARCHAR (125),
    COMPLEMENT VARCHAR (125),
    COUNTY VARCHAR (125),
    UF VARCHAR (2),
    RG VARCHAR (13),
    BIRTHDAY DATETIME,
    CONSTRAINT UC_PERSONS UNIQUE (CPF),
    PRIMARY KEY (IDPERSONS)
);

CREATE TABLE Users(
    IDUSERS INT NOT NULL,
    EMAIL VARCHAR(125) NOT NULL,
    PASSWORD VARCHAR(125) NOT NULL,
    ADMINISTRATOR BIT,
    PRIMARY KEY (IDUSERS),
    IDPERSONS INT NOT NULL,
    FOREIGN KEY (IDPERSONS) REFERENCES Persons(IDPERSONS),
    CONSTRAINT UC_USERS UNIQUE (EMAIL, IDPERSONS)
);